# Exercício de Fixação do pandas - Compras de Ecommerce  

**Nome do Aluno 1**

**Nome do Aluno 2**

Neste exercício, você receberá alguns dados falsos sobre algumas compras feitas pela Amazon. Utilize instruções da biblioteca pandas para responder as perguntas e completar as tarefas. As respostas esperadas foram deixadas no notebook. A maioria das tarefas pode ser resolvida de diferentes maneiras. 

Observe também que todas essas questões podem ser respondidas com uma linha de código.
____

**Exercício 1**: Importe pandas e leia o arquivo `compras.csv` e configure-o para um DataFrame chamado ecom.

**Exercício 2**: Mostre as 4 primeiras linhas do dataset

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04

**Exercício 3**: Quantas colunas e linhas existem nesse dataset?

(10000, 14)

**Exercício 4**: Classifique cada coluna desse dataframe de acordo com o tipo de dado (categórico ou numérico)

**Exercício 5**: Qual o valor médio de compras?

50.347302

**Exercício 6**: Qual foi o maior e o menor preço de compras desse dataset?

In [ ]:
# maior

In [13]:
# menor

0.0

**Exercício 7**: Quantas compras foram feitas no horário AM e quantas foram feitas no horário PM?

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

**Exercício 8**: Quantos clientes tem o inglês (en) como idioma de uso do site?

1098

**Exercício 9**: Quais as cinco profissões mais comuns?

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: count, dtype: int64

**Exercício 10**: Qual o preço da compra que veio do lote `90 WT`?

513    75.1
Name: Purchase Price, dtype: float64

**Exercício 11**: Qual é o email da pessoa que possui o seguinte número do cartão de crédito: `4926535242672853`?

1234    bondellen@williams-garza.com
Name: Email, dtype: object

**Exercício 12**: Qual o endereço, e-mail e profissão das pessoas têm o American Express como seu fornecedor de cartão de crédito **e** fizeram uma compra acima de US$95?

,Address,Email,Job
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",qcoleman@hunt-huerta.com,Forensic scientist
280,81060 Dustin Causeway Apt. 503\nPort Danielche...,hfarley@hicks.com,Ergonomist
372,"359 Stanley Coves\nSalasfort, SD 59457",amberhull@jones.net,Training and development officer
677,"4855 Peter Bridge\nJohnsonberg, PA 90599-0009",evanskayla@fernandez.com,Plant breeder/geneticist
766,"386 Alisha Unions\nSteelebury, ND 19782",robertsonjulia@gmail.com,"Therapist, art"
1225,"916 Amanda Heights\nNew Johnland, CA 52112-8572",lawrencecarter@kelly.com,Artist
1381,"79284 Lisa Mews Suite 069\nKellyborough, CT 71...",maldonadomichael@martinez-delgado.info,Geophysical data processor
1385,"67796 James Keys Suite 656\nSouth Katieshire, ...",vbrown@daugherty.com,Geophysical data processor
1568,"76108 Barker Manors\nEast Amy, PW 49544-5921",johnsonjulie@yahoo.com,Insurance claims handler
1727,"478 Anita Hill Apt. 766\nAverymouth, FM 50629-...",sharpmelanie@smith-johnson.com,"Psychologist, prison and probation services"
2146,"557 Barton Harbor\nFuentesport, VI 29961",jessica94@mosley-buchanan.com,Armed forces technical officer
2264,"040 Ingram Way Suite 602\nEast Matthew, AR 67341",holtamanda@gmail.com,Archaeologist
2267,"216 Olivia Court Apt. 439\nTonyshire, IN 19159...",burkestephanie@lee-cameron.com,Management consultant
2642,899 Williams Prairie Suite 234\nEast Hunterbur...,reevesmanuel@gmail.com,"Engineer, maintenance (IT)"
2828,"20135 Miller Green Apt. 763\nGarciaville, KY 6...",villarrealdavid@gray.com,Chartered management accountant
3291,"58939 Reese Cove\nSouth Ross, MA 54531",stephanieacosta@yahoo.com,IT trainer
3349,1984 Christopher Turnpike Suite 904\nRichardbu...,hgross@mccoy-mckay.info,Structural engineer
3619,"03233 Angela Road Apt. 808\nEast Jilliantown, ...",jonesjesse@castro.info,Garment/textile technologist
4071,"8161 Craig Passage Apt. 939\nPort Emilystad, R...",hhenderson@yahoo.com,Customer service manager
4569,"88284 Austin Summit Apt. 805\nKellerside, WY 6...",amy00@patton.com,Actuary
5385,USNS Smith\nFPO AA 37829,ijones@hotmail.com,Field seismologist
5655,"38674 Mckay Vista\nWilsonbury, MO 55611-8663",timothy84@hotmail.com,"Production designer, theatre/television/film"
5692,"PSC 8264, Box 8124\nAPO AE 19700",kellypace@yahoo.com,Aid worker
5814,Unit 5232 Box 4650\nDPO AE 28335-7543,jrice@gmail.com,Solicitor
5875,"8256 Anderson Forest\nFordbury, PA 81027-8980",hernandezandrea@yahoo.com,Community development worker
5895,"87003 Jason Tunnel Apt. 216\nDariusville, MS 8...",duncanmichael@hotmail.com,Event organiser
6026,Unit 4385 Box 1428\nDPO AE 04110,scott35@yahoo.com,Operations geologist
6524,"344 Rivera Shore Apt. 224\nJoshuaborough, ND 3...",olsonjohn@hotmail.com,"Teacher, primary school"
7239,"81561 Stein Rue\nEast Melissaport, MA 64959",beckerjennifer@gmail.com,"Engineer, energy"
7381,"40804 Belinda Roads Apt. 186\nWest Nicoleberg,...",woodsmatthew@walton.org,Fashion designer
7416,"1082 Jason Alley Suite 707\nWhitestad, SC 97805",gcruz@butler.com,Broadcast presenter
7514,"678 David Manor Suite 323\nBobbymouth, PW 59942",tammy75@cameron.com,Automotive engineer
8233,"327 Hamilton Hollow\nEast Nicolechester, RI 65868",elliskaren@taylor.com,Chemical engineer
8381,"274 Wallace Pine Apt. 189\nMartinberg, WY 7548...",joneswilliam@cox.net,"Surveyor, land/geomatics"
8408,Unit 4967 Box 4574\nDPO AP 11412,nunezjames@hotmail.com,"Designer, exhibition/display"
8434,"474 Gonzalez Meadow Suite 581\nEast Vincent, M...",vtaylor@hatfield.com,Armed forces technical officer
8817,"3658 Campos Lodge\nChambersfurt, MH 86260",jessica35@hotmail.com,Forensic scientist
9168,"18782 Hall Row Suite 810\nSouth Wesleyville, I...",tammyblair@yahoo.com,Computer games developer
9856,"058 Miranda Locks Suite 792\nPort Davidstad, P...",brendastewart@dalton.info,Site engineer

**Exercício 13**: Crie duas novas colunas no dataframe contendo o mês e o ano de expiração do cartão de crédito.

*Esse exercício vai precisar de mais do que uma linha de código*

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,exp_dia,exp_ano
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,02,20
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,11,18
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95,08,19
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04,02,24
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82,10,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21,03,22
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63,07,25
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98,05,21
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84,11,17
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59,02,19

**Exercício 14**: Obtenha um resumo estatístico, com a medida dos cinco números, para o valor da compra

count    10000.000000
mean        50.347302
std         29.015836
min          0.000000
25%         25.150000
50%         50.505000
75%         75.770000
max         99.990000
Name: Purchase Price, dtype: float64

**Exercício 15**: Obtenha um resumo para a variável Idioma

count     10000
unique        9
top          de
freq       1155
Name: Language, dtype: object

**Exercício 16**: Obtenha uma lista de profissões únicas nesse dataset.

array(['Scientist, product/process development', 'Drilling engineer',
       'Customer service manager', 'Fine artist', 'Fish farm manager',
       'Dancer', 'Event organiser', 'Financial manager',
       'Forensic scientist', 'Development worker, community',
       'Diagnostic radiographer', 'Surveyor, quantity',
       'Accountant, chartered public finance', 'Acupuncturist',
       'Retail manager', 'Therapist, art', 'Designer, jewellery',
       'Photographer', 'Designer, interior/spatial',
       'Public relations officer', 'Presenter, broadcasting',
       'Field seismologist', 'Musician',
       'Training and development officer', "Barrister's clerk",
       'Careers adviser', 'Scientist, research (life sciences)',
       'Recycling officer', 'Fisheries officer', 'Sales executive',
       'Civil Service fast streamer', 'Theatre stage manager',
       'Therapist, music', 'Lecturer, further education',
       'Animal technologist', 'Psychologist, occupational',
       'Music therapist', 'Minerals surveyor',
       'Tourist information centre manager', 'Tax inspector',
       'Buyer, industrial', 'Purchasing manager', 'Heritage manager',
       'Games developer', 'Facilities manager', 'Chemist, analytical',
       'Horticulturist, amenity', 'Mechanical engineer',
       'Clinical research associate', 'Technical author',
       'Radio broadcast assistant', 'Engineer, broadcasting (operations)',
       'Clothing/textile technologist', 'Holiday representative',
       'Housing manager/officer', 'Teacher, special educational needs',
       'Engineer, agricultural', 'Buyer, retail',
       'Doctor, general practice', 'Hotel manager',
       'Engineer, civil (consulting)', 'General practice doctor',
       'Jewellery designer', 'Therapist, speech and language',
       'Operational researcher', 'Graphic designer',
       'Editorial assistant', 'Financial adviser', 'Paramedic',
       'Secretary, company', 'Paediatric nurse',
       'Data processing manager', 'Print production planner',
       'Engineer, materials', 'Economist', 'Designer, furniture',
       'Human resources officer', 'Administrator',
       'Teacher, secondary school', 'Video editor',
       'Chartered certified accountant',
       'Teacher, English as a foreign language', 'Airline pilot',
       'Engineer, land', 'Legal secretary', 'Administrator, arts',
       'Dealer', 'Town planner', 'Travel agency manager',
       'Engineer, water', 'Lecturer, higher education',
       'Higher education careers adviser', 'Intelligence analyst',
       'Technical sales engineer', 'Dietitian',
       'International aid/development worker',
       'Learning disability nurse', 'Geneticist, molecular',
       'Optometrist', 'Building surveyor', 'Sports therapist',
       'Geophysical data processor', 'Multimedia programmer',
       'Research scientist (maths)', 'Social worker', 'Camera operator',
       'Interpreter', 'Furniture designer', 'Commercial horticulturist',
       'Surgeon', 'Psychotherapist, dance movement',
       'Information systems manager', 'Music tutor',
       'Merchandiser, retail', 'Insurance risk surveyor',
       'Armed forces operational officer', 'Homeopath',
       'Animal nutritionist', 'Tourism officer', 'Cabin crew',
       'Psychiatric nurse', 'Magazine features editor',
       'Chartered management accountant', 'Market researcher',
       'Mudlogger', 'Textile designer', 'Restaurant manager, fast food',
       'Medical laboratory scientific officer',
       'Chartered public finance accountant', 'Financial trader',
       'Scientist, marine', 'Environmental manager',
       'Community education officer', 'Solicitor',
       'Psychologist, clinical', 'Occupational therapist',
       'Retail merchandiser', 'Mental health nurse', 'Ophthalmologist',
       'Insurance underwriter', 'Engineer, aeronautical',
       'Chartered accountant', 'Environmental health practitioner',
       'Research scientist (life sciences)', 'Wellsite geologist',
       'Product designer', 'Armed forces technical officer',
       'Television/film/video producer', 'Water quality scientist',
       'Furniture conservator/restorer', 'Radio producer',
       'Programmer, multimedia', 'Scientist, biomedical',
       'Psychologist, sport and exercise', 'Merchant navy officer',
       'Designer, television/film set', 'Engineering geologist',
       'Health and safety inspector', 'Naval architect', 'Chiropodist',
       'Engineer, chemical', 'Scientist, research (medical)',
       'Personal assistant', 'Retail banker',
       'Advertising account planner', 'Art therapist',
       'Forest/woodland manager', 'Research scientist (medical)',
       'Scientific laboratory technician', 'Licensed conveyancer',
       'Engineer, building services', 'Energy engineer', 'Teacher, music',
       'Oncologist', 'Brewing technologist', 'Community arts worker',
       'Therapist, drama', 'Water engineer', 'Software engineer',
       'Geochemist', 'Designer, industrial/product',
       'Nature conservation officer',
       'Production designer, theatre/television/film',
       'Commercial art gallery manager', 'Exhibition designer',
       'Education officer, environmental',
       'Runner, broadcasting/film/video', 'Pharmacist, hospital',
       'Doctor, hospital', 'Teacher, adult education', 'Sub',
       'Podiatrist', 'Air broker', 'Engineer, civil (contracting)',
       'Lexicographer', 'Speech and language therapist',
       'Catering manager', 'Colour technologist', 'Surveyor, building',
       'Agricultural consultant', 'Horticultural therapist',
       'Pension scheme manager', 'Theatre manager', 'Producer, radio',
       'Scientist, forensic', 'Surveyor, insurance',
       'Hospital pharmacist', 'Surveyor, rural practice',
       'Industrial/product designer', 'Corporate treasurer',
       'Structural engineer', 'Research officer, trade union',
       'Pensions consultant', 'Secretary/administrator', 'Firefighter',
       'Database administrator', 'Health promotion specialist',
       'Operations geologist', 'Regulatory affairs officer',
       'Production assistant, radio', 'Press sub',
       'Education administrator', 'Biomedical scientist', 'Tour manager',
       'Midwife', 'Television floor manager', 'Mining engineer',
       'Interior and spatial designer', 'Engineer, energy',
       'Publishing rights manager', 'Manufacturing systems engineer',
       'Designer, exhibition/display',
       'Control and instrumentation engineer', 'Ergonomist',
       'Scientist, research (maths)', 'Psychologist, forensic',
       'Clinical scientist, histocompatibility and immunogenetics',
       'Accommodation manager', 'Administrator, sports',
       'Sports development officer', 'Educational psychologist',
       'Social research officer, government', 'Quarry manager',
       'Medical sales representative', 'Consulting civil engineer',
       'Trade union research officer', 'Financial planner',
       'Futures trader', 'Medical illustrator', 'Engineer, structural',
       'Transport planner', 'Special educational needs teacher',
       'Chiropractor', 'Therapist, sports',
       'Scientist, research (physical sciences)', 'Site engineer',
       'Psychologist, counselling', 'Bonds trader', 'Banker',
       'Proofreader', 'Social researcher', 'Analytical chemist',
       'Dramatherapist', 'Editor, commissioning', 'Sports administrator',
       'Sport and exercise psychologist', 'Garment/textile technologist',
       'Engineer, maintenance (IT)', 'Surveyor, building control',
       'Media planner', 'Statistician', 'Food technologist',
       'Chartered loss adjuster', 'Petroleum engineer',
       'Engineer, maintenance', 'Television camera operator',
       'Geoscientist', 'Printmaker', 'Artist', 'Hospital doctor',
       'Systems analyst', 'Radiographer, therapeutic',
       'Freight forwarder', 'Call centre manager', 'Theatre director',
       'Occupational psychologist', 'Communications engineer',
       'Land/geomatics surveyor', 'Advertising account executive',
       'Civil engineer, consulting', 'Medical secretary',
       'IT technical support officer', 'Advice worker',
       'Visual merchandiser', 'Nurse, mental health',
       'Further education lecturer', 'Investment banker, corporate',
       'Bookseller', 'Engineer, production', 'Health visitor',
       'Archivist', 'Recruitment consultant',
       'Conservator, museum/gallery', 'Translator', 'Youth worker',
       'Operational investment banker',
       'Radiation protection practitioner',
       'Research officer, political party', 'Make',
       'Horticulturist, commercial', 'Surveyor, hydrographic',
       'Engineer, communications', 'Surveyor, minerals', 'Hydrologist',
       'Race relations officer', 'Quantity surveyor',
       'Geologist, wellsite', 'Museum/gallery conservator',
       'Community pharmacist', 'Adult guidance worker',
       'Building control surveyor', 'Museum/gallery exhibitions officer',
       'Ambulance person', 'Probation officer', 'Orthoptist',
       'Charity officer', 'Risk analyst', 'Best boy',
       'Arts administrator',
       'Lighting technician, broadcasting/film/video',
       'Engineer, drilling', 'Engineer, control and instrumentation',
       'Medical physicist', 'Dispensing optician',
       'Management consultant', 'Commercial/residential surveyor',
       'English as a foreign language teacher', 'Engineer, site',
       'Automotive engineer', 'Air traffic controller', 'Lawyer',
       'Contracting civil engineer', 'Psychotherapist, child',
       'Maintenance engineer', 'Science writer',
       'Administrator, education', 'Administrator, Civil Service',
       'Estate manager/land agent', 'Company secretary',
       'Therapist, horticultural', 'Broadcast engineer',
       'Sound technician, broadcasting/film/video',
       'Private music teacher', 'Engineer, manufacturing',
       'Emergency planning/management officer', 'Risk manager',
       'IT consultant', 'Geographical information systems officer',
       'Equities trader', 'Immigration officer',
       'Therapeutic radiographer', 'Curator', 'Child psychotherapist',
       'Advertising art director', 'Forensic psychologist',
       'Hydrographic surveyor', 'Immunologist', 'Sports coach',
       'Haematologist', 'Waste management officer',
       'Conservator, furniture', 'Research officer, government',
       'Agricultural engineer', 'IT sales professional',
       'Armed forces logistics/support/administrative officer',
       'Field trials officer', 'Psychotherapist', 'Air cabin crew',
       'Psychiatrist', 'Illustrator', 'Marine scientist',
       'Multimedia specialist', 'Cytogeneticist',
       'Occupational hygienist', 'Charity fundraiser',
       'Planning and development surveyor', 'Counselling psychologist',
       'Physicist, medical', 'TEFL teacher',
       'Research scientist (physical sciences)', 'Fashion designer',
       'Engineer, petroleum', 'Tree surgeon',
       'Corporate investment banker', 'Public house manager',
       'Designer, textile', 'Public librarian',
       'Arts development officer', 'Actor', 'Hydrogeologist',
       'Production assistant, television', 'Embryologist, clinical',
       'Press photographer', 'Marketing executive',
       'Television production assistant', 'Early years teacher',
       'Landscape architect', 'Librarian, academic', 'Web designer',
       'Health service manager', 'Clinical psychologist',
       'Exercise physiologist', 'Electrical engineer',
       'Psychologist, prison and probation services',
       'Journalist, magazine', 'Dance movement psychotherapist',
       'Animator', 'Legal executive', 'Plant breeder/geneticist',
       'Manufacturing engineer', 'Microbiologist', 'Biochemist, clinical',
       'Broadcast presenter', 'Ranger/warden',
       'Programme researcher, broadcasting/film/video', 'Dentist',
       'Aid worker', 'Publishing copy', 'Environmental education officer',
       'Librarian, public', 'Phytotherapist', 'Nurse, adult',
       'Programmer, systems', 'Scientist, physiological',
       'Secondary school teacher', 'Media buyer', 'Trade mark attorney',
       'Editor, film/video', 'Careers information officer',
       'Retail buyer', 'Ship broker', 'Lobbyist', 'Location manager',
       'Surveyor, mining', 'Systems developer', 'Optician, dispensing',
       'Chemical engineer', 'Oceanographer', 'Patent attorney',
       'Passenger transport manager', 'Glass blower/designer',
       'Psychologist, educational', 'Education officer, museum',
       'Patent examiner', 'Logistics and distribution manager',
       'Trading standards officer', 'Seismic interpreter',
       'Local government officer', 'Clinical cytogeneticist',
       'Biomedical engineer', 'Diplomatic Services operational officer',
       'Land', 'Surveyor, planning and development', 'Farm manager',
       'Claims inspector/assessor', 'Warden/ranger',
       'Civil engineer, contracting', 'Clinical molecular geneticist',
       'Surveyor, land/geomatics', 'Therapist, nutritional',
       'Historic buildings inspector/conservation officer',
       'English as a second language teacher', 'Materials engineer',
       'Insurance broker', 'Ecologist', 'Production manager',
       'Veterinary surgeon', 'Pilot, airline', "Nurse, children's",
       'Astronomer', 'Architect', 'Conservation officer, nature',
       'Personnel officer', 'Network engineer', 'Investment analyst',
       'Writer', 'Designer, fashion/clothing', 'Theme park manager',
       'Engineer, electrical', 'Art gallery manager', 'Office manager',
       'Pharmacologist', 'Meteorologist', 'Estate agent',
       "Politician's assistant", 'Environmental consultant', 'Osteopath',
       'Amenity horticulturist', 'Physiological scientist',
       'Public relations account executive',
       'Senior tax professional/tax inspector', 'Arboriculturist',
       'Radiographer, diagnostic', 'Engineer, automotive',
       'Editor, magazine features', 'Sales professional, IT',
       'Commissioning editor', 'Ceramics designer',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Geologist, engineering', 'Designer, multimedia',
       'Engineer, manufacturing systems', 'Clinical embryologist',
       'Medical technical officer', 'Teacher, primary school',
       'Set designer', 'Producer, television/film/video',
       'Education officer, community',
       'Conservation officer, historic buildings',
       'Insurance account manager', 'Financial controller',
       'Film/video editor', 'Museum/gallery curator',
       'Accounting technician', 'Stage manager', 'Physiotherapist',
       'Sales promotion account executive', 'Horticultural consultant',
       'Journalist, broadcasting', 'Health and safety adviser',
       'Building services engineer',
       'Product/process development scientist', 'Metallurgist',
       'Audiological scientist', 'Designer, blown glass/stained glass',
       'Tax adviser', 'Industrial buyer',
       'Government social research officer',
       'Outdoor activities/education manager', 'Solicitor, Scotland',
       'Conference centre manager', 'Health physicist',
       'Pharmacist, community', 'Applications developer',
       'Public affairs consultant', 'Prison officer',
       'Production engineer', 'Actuary', 'Museum education officer',
       'Fitness centre manager', 'Records manager',
       'Journalist, newspaper', 'Computer games developer',
       'Toxicologist', 'Counsellor', 'Therapist, occupational',
       'Accountant, chartered certified', 'Insurance claims handler',
       'Programmer, applications', 'Accountant, chartered management',
       'Broadcast journalist', 'Energy manager', 'Barrister',
       'Scientist, audiological', 'Designer, graphic', 'Cartographer',
       'Community development worker', 'Engineer, mining',
       'Special effects artist', 'Gaffer', 'Civil Service administrator',
       'Armed forces training and education officer', 'Quality manager',
       'Engineer, electronics', 'Development worker, international aid',
       'Restaurant manager', 'Architectural technologist',
       'Academic librarian', 'Fast food restaurant manager',
       'Rural practice surveyor', 'Designer, ceramics/pottery',
       'Police officer', 'Soil scientist', 'Technical brewer',
       'Administrator, local government', 'Copywriter, advertising',
       'Volunteer coordinator', 'Magazine journalist',
       'Information officer', 'Copy', 'Advertising copywriter',
       'Engineer, biomedical', 'Nurse, learning disability',
       'Aeronautical engineer', 'Archaeologist', 'IT trainer',
       'Clinical biochemist',
       'Administrator, charities/voluntary organisations', 'Pathologist',
       'Geophysicist/field seismologist',
       'Investment banker, operational', 'Teacher, early years/pre',
       'Electronics engineer', 'Exhibitions officer, museum/gallery',
       'Nutritional therapist', 'Teaching laboratory technician',
       'Herbalist', 'Leisure centre manager', 'Higher education lecturer',
       'Newspaper journalist', 'Accountant, chartered',
       'Loss adjuster, chartered', 'Surveyor, commercial/residential',
       'Warehouse manager', 'Scientist, water quality',
       'Primary school teacher',
       'Chartered legal executive (England and Wales)',
       'Telecommunications researcher', 'Equality and diversity officer',
       'Learning mentor', 'Financial risk analyst',
       'Engineer, technical sales', 'Adult nurse'], dtype=object)

**Exercício 17**: Mostre o número de compras feitas por cada categoria profissional no e-commerce.

Job
Academic librarian                  11
Accommodation manager               17
Accountant, chartered               20
Accountant, chartered certified     18
Accountant, chartered management    15
                                    ..
Water quality scientist             18
Web designer                        20
Wellsite geologist                  24
Writer                              10
Youth worker                        18
Name: Job, Length: 623, dtype: int64

**Exercício 18**: Mostre o maior valor gasto por cada categoria profissional no e-commerce.

Job
Academic librarian                  95.15
Accommodation manager               80.78
Accountant, chartered               98.54
Accountant, chartered certified     96.78
Accountant, chartered management    99.90
                                    ...
Water quality scientist             95.60
Web designer                        95.84
Wellsite geologist                  98.42
Writer                              92.33
Youth worker                        98.62
Name: Purchase Price, Length: 623, dtype: float64

**Exercício 19**: Agrupe os dados por idioma e mostre o número de compras, a média e o desvio padrão para cada agrupamento.

           len       mean        std
Language
de        1155  50.254485  29.043419
el        1137  51.555356  28.685787
en        1098  51.103015  28.504003
es        1095  49.366977  29.189423
fr        1097  49.476718  29.475620
it        1086  50.001004  29.331665
pt        1118  51.215546  28.552595
ru        1155  49.927134  28.994335
zh        1059  50.180198  29.406322

**Exercício 20**: Agrupe os dados por categoria funcional e idioma. Mostre o número de compras para cada um desses agrupamentos

                             len
Job                Language
Academic librarian de          1
                   el          3
                   en          2
                   es          2
                   fr          1
...                          ...
Youth worker       en          1
                   es          3
                   fr          5
                   it          1
                   pt          1

[4647 rows x 1 columns]

**Exercício 21**: Mostre o dataframe ordenado por idioma e empresa.

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
4727,"PSC 2426, Box 0661\nAPO AP 07395-0585",39 AK,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_9 ...,"Acevedo, Smith and Higgins",379362333559554,09/22,968,Voyager,brownkristi@hotmail.com,Social researcher,215.171.158.181,de,58.18
6866,"60922 Robert Villages\nNew George, MP 82575",94 cz,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows CE;...,Acosta-Lee,4150024452234388,05/20,793,JCB 16 digit,timothygregory@wilson.com,Analytical chemist,28.98.175.5,de,65.38
8933,"3848 Janet Plaza\nJasonstad, CA 99690",07 yM,AM,Opera/9.59.(X11; Linux i686; en-US) Presto/2.9...,Adams LLC,377559932403678,03/19,1704,JCB 16 digit,tina77@chen-flores.org,"Psychologist, forensic",31.166.46.126,de,94.80
3219,"484 Brandon Park Apt. 164\nPort Jeremyton, SC ...",47 zi,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_9...,Adams Ltd,869990568650941,12/24,4401,Maestro,svaughn@williams.com,Clinical biochemist,40.146.27.55,de,77.57
5392,"4066 Matthew Dam\nLindaville, ME 70257",87 YL,PM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Adams, Christian and Rodriguez",4701741874669396,01/19,6465,Mastercard,mwalker@fisher.biz,Health visitor,130.67.117.203,de,22.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6209,USNS Turner\nFPO AE 37707-2767,91 gc,AM,Opera/9.63.(Windows 95; en-US) Presto/2.9.174 ...,Young-Nguyen,4969507957694560,02/17,962,JCB 16 digit,martinezamanda@davis.net,Chartered accountant,78.163.128.160,zh,25.59
538,"249 Scott Loop\nSouth John, SC 82732-9487",77 mh,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5...,Zamora Inc,869926086984214,10/18,171,JCB 16 digit,shelbymalone@choi-morris.com,"Research officer, political party",116.178.252.126,zh,83.59
8496,"7185 Rivera Tunnel Apt. 837\nMeganberg, ME 450...",79 uX,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Zamora-Leon,3096246227245196,11/25,53,Diners Club / Carte Blanche,cynthiamurray@yahoo.com,Product/process development scientist,192.58.132.188,zh,65.14
199,"06825 Shannon Glen Suite 582\nLake Evelyn, GU ...",71 ZP,AM,Mozilla/5.0 (Windows; U; Windows NT 6.2) Apple...,"Zuniga, Cooper and Smith",210022920848132,08/25,108,JCB 16 digit,millerraymond@hotmail.com,Theatre stage manager,28.81.204.206,zh,29.39
4972,"52271 Zachary Tunnel Suite 025\nFarleyside, NV...",74 tK,PM,Mozilla/5.0 (compatible; MSIE 6.0; Windows CE;...,"Zuniga, Morris and Smith",341151057315326,10/23,88,VISA 13 digit,nicole72@brown.com,Research scientist (medical),248.169.119.242,zh,34.43